language: python
install:
  - pip install coveralls pytest-cov nltk
  - pip install .
before_script:
  - python -m nltk.downloader punkt
  - python -m nltk.downloader averaged_perceptron_tagger
  - python -m nltk.downloader wordnet
script:
  - pytest --cov=vocabulary_generator
after_success:
  - coveralls
